# Generated by Django 5.0.6 on 2024-07-06 11:54

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='mailing_no_name', max_length=150, verbose_name='название рассылки')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата начала рассылки')),
                ('end_date', models.DateTimeField(default=datetime.datetime(2024, 7, 7, 11, 54, 18, 897407, tzinfo=datetime.timezone.utc), verbose_name='дата окончания рассылки')),
                ('next_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='следующая дата рассылки')),
                ('interval', models.CharField(choices=[('per_day', 'раз в день'), ('per_week', 'раз в неделю'), ('per_month', 'раз в месяц')], default='per_day', max_length=50, verbose_name='интервал рассылки')),
                ('status', models.CharField(choices=[('not_active', 'не активна'), ('is_active', 'запущена'), ('finished', 'закончена успешно'), ('finished_date', 'закончена по сроку'), ('finished_error', 'законечена с ошибками')], default='not_active', max_length=50, verbose_name='статус рассылки')),
                ('client', models.ManyToManyField(to='clients.client', verbose_name='Клиент')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'параметры рассылки',
                'verbose_name_plural': 'параметры рассылок',
                'permissions': [('change_status', 'Can change status')],
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_mailing', models.DateTimeField(auto_now=True, null=True, verbose_name='дата и время последней рассылке')),
                ('status_mailing', models.CharField(blank=True, max_length=50, null=True, verbose_name='статус попытки')),
                ('response', models.CharField(blank=True, max_length=255, null=True, verbose_name='ответ почтового сервера')),
                ('mailing_parameters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailings.mailingparameters', verbose_name='Параметры рассылки')),
            ],
            options={
                'verbose_name': 'лог рассылки',
                'verbose_name_plural': 'логи рассылок',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='тема письма')),
                ('content', models.TextField(blank=True, null=True, verbose_name='содержание письма')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель')),
            ],
            options={
                'verbose_name': 'письмо',
                'verbose_name_plural': 'письма',
            },
        ),
        migrations.AddField(
            model_name='mailingparameters',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailings.message', verbose_name='Содержание письма'),
        ),
    ]
