# Generated by Django 5.0.6 on 2024-07-07 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingparameters',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 8, 12, 16, 56, 351075, tzinfo=datetime.timezone.utc), verbose_name='дата окончания рассылки'),
        ),
    ]
