# Generated by Django 5.0.6 on 2024-07-07 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_alter_mailingparameters_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingparameters',
            options={'permissions': [('deactivate_mailing', 'Can deactivate mailing'), ('view_all_mailings', 'Can view all mailings')], 'verbose_name': 'параметры рассылки', 'verbose_name_plural': 'параметры рассылок'},
        ),
        migrations.AlterField(
            model_name='mailingparameters',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 8, 13, 38, 29, 606343, tzinfo=datetime.timezone.utc), verbose_name='дата окончания рассылки'),
        ),
    ]
