# Generated by Django 5.0.6 on 2024-07-07 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_alter_mailingparameters_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingparameters',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 8, 13, 38, 58, 991003, tzinfo=datetime.timezone.utc), verbose_name='дата окончания рассылки'),
        ),
    ]
